---
title: "List of Links"
page-layout: article
format: html
---

Before (good) search engines, we relied on lists of links on web pages we already knew how to find. For all of the magic an algorithmic recommendation system evinces, this is still a damn fine way to discover stuff you might like.

**Stuff I've made or contributed to that I think you'd like to know about:**

- [The Developer Science Review {{< fa solid square-up-right>}}](https://dsl.pubpub.org){target=new} is a collection of scholarly work curated by the former Developer Success Lab.
- [jflournoy/verse-cmdstan](https://hub.docker.com/r/jflournoy/verse-cmdstan) is a Docker image based on rocker/verse with `cmdstan`, `cmdstanr`, and other goodies built on top [<i class="fa-brands fa-github"></i>](https://github.com/jflournoy/verse-cmdstan/blob/main/Dockerfile)
- [local]{.badge-vapor .small} [Random Intercept Cross-Lagged Panel Model Tutorial](./riclpm-lavaan-demo.html)
  - This is a tutorial I made a very, very, very long time ago that folks are still finding really helpful.
- [local]{.badge-vapor .small} [How to plan and preregister a multiverse analysis](./multiverse-preregistration/)
  - I and some good friends worked on a bunch of multiverse (aka specification-curve) analyses together and gathered our experiences and thoughts into this brief guide. It even has an awesome shiny app that [Dani Cosme, PhD](https://dcosme.github.io/), made.
- [A collection of images of maps on Unsplash I use as rotating new-tab backgrounds](https://unsplash.com/collections/-QxzbVy07E4/maps-of-interest)
  - There wasn't a collection that targeted maps (and nothing else, excluding images of, e.g., people holding maps). I use the term "map" a little bit broadly to also include renderings of topographic data and e.g., needlepoint of middle-earth.
- [local]{.badge-vapor .small} [How hiring could distort the (lack of) association between programming performance and agreeableness](https://johnflournoy.science/hiring-collider/)
  - Everyone loves to learn about collider bias.
- [giftwrapr <i class="fa-brands fa-github"></i>](https://github.com/jflournoy/giftwrapr) is an R package to make generating Docker containers for your project easy. 

**Stuff on the world wide web:**

- [A list of authors and books (of fiction) that use extensive footnotes or indexing](https://www.miskatonic.org/footnotes.html)
  - Thanks to [Finn Brunton](https://sts.ucdavis.edu/people/finn-brunton) for my first introduction, in one of his undergraduate essays, to the delight of footnotes.
- [The website of Gene Keyes, author of the Cahill-Keyes map](https://www.genekeyes.com/index.html)
  - This is a paragon exemplar of early internet website design, and hosts a wealth of thinking on map making, such as [this scathing review of the Fuller Dymaxion map](https://genekeyes.com/FULLER/BF-1-intro.html)
- More coming soon!
